### ISSUE TITLE
BehavesLike.Win32.AdwareFileTour.gc detected on VirusTotal

### ISSUE THREAD

**Issue by crssi** [troylar/quiet-on-the-set#13]
FYI: [https://www.virustotal.com/#/file/0a11604544b4b1fd4a7cbccd927f55b18242b5ba68fde72f62861c6ba993be97/detection](https://www.virustotal.com/#/file/0a11604544b4b1fd4a7cbccd927f55b18242b5ba68fde72f62861c6ba993be97/detection)

**Comment by karolzlot** [comment]
only 3 scanners not very popular scanners, likely false alarm
