### ISSUE TITLE
Can't uninstall Quiet on the Set

### ISSUE THREAD

**Issue by danielpyon** [troylar/quiet-on-the-set#15]
I tried to uninstall Quiet on the Set (Windows 10 64bit) using the add or remove programs app, but it does not properly uninstall, because it still has an icon in my taskbar (and I am still able to use it by clicking on the smiley face icon).

**Comment by karolzlot** [comment]
It can be disabled from startup by https://www.nirsoft.net/utils/what_run_in_startup.html

**Comment by CrystalENVT** [comment]
@danielpyon I was having the same issue, & you can go to `C:\Program Files (x86)` & delete the folder `Quiet on the Set` to get rid of it

**Comment by THANKYOUmanyouarecool** [comment]
THANK YOU CRYSTAL SPORE

**Comment by THANKYOUmanyouarecool** [comment]
> @danielpyon I was having the same issue, & you can go to `C:\Program Files (x86)` & delete the folder `Quiet on the Set` to get rid of it

thanks i couldnt get rid so i found this and thank you
