### ISSUE TITLE
Allow values between intervals of 5

### ISSUE THREAD

**Issue by jphui** [troylar/quiet-on-the-set#4]
As the title states, it would be nice to have the option to set it to "7" or "23" rather than have it only be able to set to increments of 5.

Would recommend some sort of text box to edit the volume rather than the slider, or at least in conjunction with the slider as well.

By the way, really nice work! Of all the Volume Lock options I have seen, this is the single best!!!

**Comment by troylar** [comment]
Yea, I can tackle this pretty quickly.

**Comment by jphui** [comment]
Just realized that I was not sliding the slider correctly. You can close this issue now.

However, there seems to be a bug where, when the window is closed then reopened, the Unlock function does not work and the previously-set max volume is stuck.
